server:
  port: ${PORT:8081}
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: backend-marketstare-search
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://avenash:UqPdlVMkyLrANdFB@cluster-market-stare.nzz0g.mongodb.net/myFirstDatabase?retryWrites=true&w=majority}
      database: ${MONGODB_DATABASE:test}
      auto-index-creation: true

security:
  username: ultimate
  password: $2a$10$TzSJoEzPMlJ.n7TxNepvyOq1TYNOaWsnftm9gjgnKh4aIbrecy8Ji
  role: ADMIN
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5000
    - https://market-stare.web.app
    - https://marketstare.com

market:
  data:
    rapidapi:
      yahoo:
        lowlatency:
          options:
            host: yfapi.net
            apikey: ${RAPID_API_YAHOO_LOW_LATENCY:L2Bo7U0NLJ5l0XDOSNpkm9E2yZvzk3YT8YKuyC1G}
            endpoint: https://${market.data.rapidapi.yahoo.lowlatency.options.host}/v7/finance/options/{ticker}
    yahoo:
      api-endpoint: https://query1.finance.yahoo.com/v8/finance/chart
    alphavantage:
      apikey: ${ALPHAVANTAGE_API_KEY:demo}
      api-endpoint: https://www.alphavantage.co/query

management:
  endpoints:
    web:
      exposure:
        include: '*'