# openapi2-functions.yaml
swagger: '2.0'
info:
  title: backend-alphavantage-search api-backend-alphavantage-search
  description: API alphavantage-search for marketstare
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /backend-marketstare-search/actuator/health:
    get:
      summary: API health check
      operationId: /backend-marketstare-search/actuator/health
      x-google-backend:
        address: https://backend-marketstare-search-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM]
      responses:
        '200':
          description: Successful response from /backend-marketstare-search/actuator/health
          schema:
            type: string
  /backend-marketstare-search/api/v1/all/tickers:
    get:
      summary: Returns all tickers
      operationId: /backend-marketstare-search/api/v1/all/tickers
      x-google-backend:
        address: https://backend-marketstare-search-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM]
      responses:
        '200':
          description: Successful response from /backend-marketstare-search/api/v1/all/tickers
          schema:
            type: string
  /backend-marketstare-search/api/v1/latestupdate/find/symbol/{symbol}:
    get:
      summary: Returns latest price of provided ticker
      operationId: /backend-marketstare-search/api/v1/latestupdate/find/symbol/{symbol}
      x-google-backend:
        address: https://backend-marketstare-search-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM ]
      parameters:
        - in: "path"
          name: "symbol"
          required: true
          type: "string"
      responses:
        '200':
          description: Successful response from /backend-marketstare-search/api/v1/latestupdate/find/symbol/{symbol}
          schema:
            type: string
  /backend-marketstare-search/api/v1/overview/find/symbol/{symbol}:
    get:
      summary: Returns company's overview w.r.t provided ticker
      operationId: /backend-marketstare-search/api/v1/overview/find/symbol/{symbol}
      x-google-backend:
        address: https://backend-marketstare-search-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM ]
      parameters:
        - in: "path"
          name: "symbol"
          required: true
          type: "string"
      responses:
        '200':
          description: Successful response from /backend-marketstare-search/api/v1/overview/find/symbol/{symbol}
          schema:
            type: string
  /backend-marketstare-data-ingestion/actuator/health:
    get:
      summary: API health check
      operationId: /backend-marketstare-data-ingestion/actuator/health
      x-google-backend:
        address: https://backend-marketstare-data-ingestion-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM ]
      responses:
        '200':
          description: Successful response from /backend-marketstare-data-ingestion/actuator/health
          schema:
            type: string
  /backend-marketstare-data-ingestion/api/v1/sentiment/analysis/blacklist/vocab/save:
    post:
      summary: API to store blacklist vocab for sentiment analysis
      operationId: /backend-marketstare-data-ingestion/api/v1/sentiment/analysis/blacklist/vocab/save
      x-google-backend:
        address: https://backend-marketstare-data-ingestion-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM ]
      responses:
        '200':
          description: Successful response from /backend-marketstare-data-ingestion/api/v1/sentiment/analysis/blacklist/vocab/save
          schema:
            type: string
  /backend-marketstare-data-ingestion/api/v1/sentiment/analysis/helper/vocab/save:
    post:
      summary: API to store helper vocab for sentiment analysis
      operationId: /backend-marketstare-data-ingestion/api/v1/sentiment/analysis/helper/vocab/save
      x-google-backend:
        address: https://backend-marketstare-data-ingestion-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM ]
      responses:
        '200':
          description: Successful response from /backend-marketstare-data-ingestion/api/v1/sentiment/analysis/helper/vocab/save
          schema:
            type: string
  /backend-marketstare-data-ingestion/api/v1/reddit/submission/save:
    post:
      summary: API to store reddit submissions
      operationId: /backend-marketstare-data-ingestion/api/v1/reddit/submission/save
      x-google-backend:
        address: https://backend-marketstare-data-ingestion-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM ]
      responses:
        '200':
          description: Successful response from /backend-marketstare-data-ingestion/api/v1/reddit/submission/save
          schema:
            type: string
  /backend-news-api/actuator/health:
    get:
      summary: API health check
      operationId: /backend-news-api/actuator/health
      x-google-backend:
        address: https://backend-news-api-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM ]
      responses:
        '200':
          description: Successful response from /backend-news-api/actuator/health
          schema:
            type: string
  /backend-news-api/api/v1/list/news:
    post:
      summary: API to fetch news w.r.t ticker and countryCode
      operationId: /backend-news-api/api/v1/list/news
      x-google-backend:
        address: https://backend-news-api-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM ]
      responses:
        '200':
          description: Successful response from /backend-news-api/api/v1/list/news
          schema:
            type: string
  /backend-news-api/api/v1/news/details/{region}/{newsId}:
    get:
      summary: Redirects to news page w.r.t region and newsId (received from /backend-news-api/api/v1/list/news)
      operationId: /backend-news-api/api/v1/news/details/{region}/{newsId}
      x-google-backend:
        address: https://backend-news-api-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM ]
      parameters:
        - in: "path"
          name: "region"
          required: true
          type: "string"
        - in: "path"
          name: "newsId"
          required: true
          type: "string"
      responses:
        '200':
          description: Successful response from /backend-news-api/api/v1/news/details/{region}/{newsId}
          schema:
            type: string
  /api/v1/reddit/submissions/{query}:
    get:
      summary: Returns reddit submission w.r.t provided query e.g. aapl|apple
      operationId: reddit-posts
      x-google-backend:
        address: https://backend-marketstare-reddit-co4tcjxfmq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: [ AIzaSyDqyDp6sFeU2PTN8RrT6ZTRUQB-s06tgmU, AIzaSyBESHznQRBHBjPmYs6-SYptov_vzmAMAUM ]
      parameters:
        - in: "path"
          name: "query"
          required: true
          type: "string"
      responses:
        '200':
          description: Successful response from /reddit/submissions/{query}
          schema:
            type: string
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"